pipeline 
{
    agent any
    stages 
    {
        stage('Test') 
        {
            steps 
            {
                sh 'python3 main.py'
            }
        }
        stage('Confirm') 
        {
            steps 
            {
                sh 'echo Pipeline success'
            }
        }
    }
}

// node{
//     docker.image('nginx:latest').withRun('-p 80:80'){ c ->
//     sh 'docker ps'
//     sh 'curl localhost'
//     }
// }