def pipelineContext = [:]

node
{
    def registryProjet = 'localhost:5000/dockindock'
    def IMAGE = "${registryProjet}:version-${env.BUILD_ID}"

    echo "IMAGE = $IMAGE"

    stage('Clone'){
        checkout scm
    }

    def img = stage('Build')
    {
        docker.build("$IMAGE", './TestJenkinsRegistry')
    }
    stage('Run')
    {
        img.withRun("--name run-$BUILD_ID -p 80:80"){ c ->
            sh 'echo "Run success"'
        }
    }
    stage('Push')
    {
        docker.withRegistry('http://localhost:5000')
        {
            img.push 'latest'
            img.push()
        }
    }
}