def pipelineContext = [:]

node
{
    def registryProjet = 'TestJenkinsDocker/dockerfile'
    def IMAGE = "$(registryProjet):version-${env.BUILD_ID}"

    echo "IMAGE = $IMAGE"

    def img = stage('Build')
    {
        docker.build("$IMAGE", '.')
    }
    stage('Run')
    {
        img.withRun("--name run-$BUILD_ID -p 80:80"){ c ->
            sh 'echo "Run success"'
        }
    }
    stage('Push')
    {
        docker.withRegistry('https://registry.gitlab.com','reg1')
        {
            img.push 'latest'
            img.push()
        }
    }
}